# Generated by Django 4.2.3 on 2023-07-29 03:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter first name', max_length=250)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=250)),
                ('mobile_number', models.IntegerField(help_text='Enter mobile number')),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter product name', max_length=250)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('product_active', models.BooleanField(default=True)),
                ('product_added_on', models.DateField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapi.customer')),
                ('catagories', models.ManyToManyField(to='shopapi.category')),
            ],
            options={
                'ordering': ['-product_added_on'],
            },
        ),
    ]
