# Generated by Django 4.2.3 on 2023-07-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapi', '0004_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
