# Generated by Django 4.2.3 on 2023-07-29 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shopapi', '0005_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagories',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
